### ISSUE TITLE
Possible man in the middle attack due to not enforcing HTTPS in the account page

### ISSUE THREAD

**Issue by s1155031145** [ierg4210/shop43#4]
1.Detailed steps to reproduce? Login in the page http://store43.ierg4210.org/account/login
What did you see? When I use Wireshark to capture the wifi data, I can see clearly in plaintext the username together with the password.
What did you expect to see?Login credentials should not be exposed in plaintext.
What is the possible fix? Should enforce HTTPS in all the login page.

Proof. http://postimg.org/image/z081n57jn/

**Comment by Milanvdm** [comment]
The admin login page is enforced with HTTPS.
The specifications of the assignment didn't ask to enforce the HTTPS protocol on the account login page.
But of course, you are completely right.
