### ISSUE TITLE
[P3B-3] Shopping list information 

### ISSUE THREAD

**Issue by s1155030186** [ierg4210/shop43#5]
Your shopping list is store on localStorage with following data:
{oid,name, price, amount}

In requirement, it should be store {pid, number}
request {prod_name, price} from AJAX

Users may change the localStorage so that users can buy products to be a lower cost

It expected to change back to a normal product information by sending request to server
![11117711_10205666194108087_1158252681_n](https://cloud.githubusercontent.com/assets/10598196/7539387/3f95b83a-f5d9-11e4-811f-93fb2d7b48a7.jpg)
![11257717_10205666194468096_119873666_n](https://cloud.githubusercontent.com/assets/10598196/7539399/4ee8b68e-f5d9-11e4-8e93-43a205c83bf5.jpg)

From the photo, we can see that when product is updated, the shopping list would not updated. The wrong decision may be made due to wrong. Or you send the whole things to server and server does not check the relation of the product, it will receive an unexpected total from the client.

prossible fix: Request the price and name by ajax request by using (pid,quantity) and not trust the client local storage directly

**Comment by Milanvdm** [comment]
The server will check everything on the serverside.
It only checks the sent pid and quantity. Based on those values, it will calculate the price and charge
you accordingly.

**Comment by s1155030186** [comment]
I see your point. I just want to say this may make inconvenience to customer if any Browser hijacking is being on the customer side which change the content in the local storage which may cause a worse user experience . 
btw Thanks for your reply

**Comment by zhusz** [comment]
Invalid hacking.
